//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ebedrendeles_adatbazis
{
    using System;
    using System.Collections.Generic;
    
    public partial class enEtelek
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enEtelek()
        {
            this.enAlacarte = new HashSet<enAlacarte>();
        }
    
        public int etelekID { get; set; }
        public string kategoria { get; set; }
        public string nev { get; set; }
        public int ar { get; set; }
        public byte[] kep { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enAlacarte> enAlacarte { get; set; }
    }
}
