//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ebedrendeles_adatbazis
{
    using System;
    using System.Collections.Generic;
    
    public partial class enFelhasznalo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enFelhasznalo()
        {
            this.enRendeles = new HashSet<enKosar>();
        }
    
        public int felhasznaloID { get; set; }
        public string felhasznalonev { get; set; }
        public string jelszo { get; set; }
        public string email { get; set; }
        public string vezeteknev { get; set; }
        public string keresztnev { get; set; }
        public int iranyitoszam { get; set; }
        public string varos { get; set; }
        public string cim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enKosar> enRendeles { get; set; }
    }
}
