//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ebedrendeles_adatbazis
{
    using System;
    using System.Collections.Generic;
    
    public partial class enNetelek
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enNetelek()
        {
            this.enHrendeles = new HashSet<enMenu>();
        }
    
        public int napietelekID { get; set; }
        public string leves { get; set; }
        public string foetel1 { get; set; }
        public string foetel2 { get; set; }
        public string foetelvega { get; set; }
        public string desszert { get; set; }
        public System.DateTime datum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enMenu> enHrendeles { get; set; }
    }
}
